### PR TITLE
Oval time

### PR DESCRIPTION
**Pull request by Schwad**
image

Oh we are getting there! I want this oval to not just support the basic `oval 1 2 3 4` but also `oval 1 2 3` and oval defined with only kwargs

Here's the manual

This is a WIP - becauuuuse I still haven't gotten fill color and stroke color to work yet.

But anyway this has been a really helpful exercise so far! [Oval manual bit to review](https://github.com/scarpe-team/scarpe/blob/main/docs/static/manual.md#ovalleft-top-radius--shoesshape)

But if you search oval is referenced in the manual like, 45 times in other places and in the examples. 

Part of me wonders if I should default oval as `center: true`. Which is weird because the examples use `center: true`. But it is possible that the examples and style varied over time and I'm really tempted to think that the author's intent is to have the thing centered from top left being truly top left.

so I might update that.

THIS HAS BEEN FUN

### CODE REVIEW

**Comment by noahgibbs** [comment]
Ooh! This got some *interesting* test failures in CI. I do *not* think they are because of your changes here. https://github.com/scarpe-team/scarpe/actions/runs/5213564306/jobs/9408717569?pr=213

**Comment by Schwad** [comment]
> Ooh! This got some *interesting* test failures in CI. I do *not* think they are because of your changes here. https://github.com/scarpe-team/scarpe/actions/runs/5213564306/jobs/9408717569?pr=213

I also think some of our widgets are going to struggle when listed more than once or nested inside of stacks or flows and we haven't really been testing that in our examples

And I'd also like to start comparing outputs with shoes3 outputs or shoes4 outputs where possible. Though that is more manual and more toil 😬

**Comment by Schwad** [comment]
Wow! Yes really interesting failures!

**Comment by Schwad** [comment]
let's see if any failures change with a rebase

**Comment by noahgibbs** [comment]
So, at this point, pretty sure this has been replaced by #324, so I'm closing this. @schwad feel free to re-open if I'm misunderstanding.

**Pull request closed without merging**
