### PR TITLE
Really quick Shoes API explorer example

### PR DESCRIPTION
**Pull request by noahgibbs**
### Description

This is an example Shoes app that checks a list (derived from Shoes-core) of Shoes API methods and sees which ones the Shoes object actually responds to, putting the list in a Shoes window.

### Image

Screenshot 2023-06-28 at 20 43 54

### Checklist

- [X] Run tests locally
- [ ] Run linter(check for linter errors)

### CODE REVIEW

**Comment by noahgibbs** [comment]
This is how Shoes3 rates on API coverage when I check the same thing:

Screenshot 2023-06-29 at 11 13 32

So that's full coverage of the "art", "animate" and "element" categories. No "keyrelease" or "scrolltop" in interaction, but the rest are there. Only image, no video or sound in media. No "setup" (which only has one.) No "style", but all the other individual style bits in "style". And no "fg" or "bg", but all the rest available in "text".

That also doesn't show certain things like "svg" that Shoes3 has and Shoes4-Core does *not* have. The list is just from Shoes4-Core. I also didn't put the builtins into this program, so it's not showing the stuff defined on Kernel instead of Shoes::App.

**Comment by noahgibbs** [comment]
Also Shoes3 has significantly different colour and newline handling than we do, as you can see from the two screenshots.

**Comment by noahgibbs** [comment]
Also Shoes3 has significantly different colour and newline handling than we do, as you can see from the two screenshots.

**Review by Schwad — APPROVED** [review]
Oh wow. I would never have thought of this

**Comment by noahgibbs** [comment]
I'm thrilled that it's capable enough to be useful, but also screwy enough that I'll want to keep fixing stuff for it :-)

**Pull request merged**
