### PR TITLE
Add border as drawable

### PR DESCRIPTION
**Pull request by sapienfrom2000s**
### Description

Move from border as style to border as drawable element

maybe solves #498 

### Image(if needed, helps for a faster review)

border

### Checklist

- [ ] Run tests locally

### CODE REVIEW

**Review by noahgibbs — APPROVED** [review]

**Comment by noahgibbs** [comment]
Sorry for taking awhile to get to this... But it looks like some tests are failing. I'll try to look into this soon.

**Comment by sapienfrom2000s** [comment]
It seems like I need to consider gradient and curve as well

**Comment by gintama91** [comment]
I think generating fixtures should fix that `background_with_image` test too

`bundle exec rake test:regenerate_html_fixtures`

**Comment by noahgibbs** [comment]
Nice! Tests passing, merged.

**Pull request merged**
