### PR TITLE
Include Scarpe::Colors into Scarpe::Widget

### PR DESCRIPTION
**Pull request by noahgibbs**
Convert everything to RGB, and do our own conversions.
Use an integer alpha 0-255 with integer colors, and a float alpha with float colors.

### CODE REVIEW

**Comment by Schwad** [comment]
This is a great idea as we generally agree on colors on that higher level

**Comment by noahgibbs** [comment]
We also have examples that use these methods, which at first I didn't realise. So we need to pass them through somehow in any case (though it'd be possible to pass them through as, like, names or something.)

**Review by Schwad — APPROVED** [review]

**Comment by Schwad** [comment]
I believe this one is ready to roll right? I'm merging away

**Comment by noahgibbs** [comment]
Yup! Thanks.

**Pull request merged**
