### PR TITLE
Added new Para Styles

### PR DESCRIPTION
**Pull request by Nj221102**
### Description
Added some more para styles like font-variant, font 
updated some para styles like font-family, emphasis

emphasis wasn't working before because it wasn't mentioned in shoes styles in lacci/lib/shoes/drawables/para.rb
font-family was mentioned as font in shoes styles so i changed it to family .

```
Shoes.app do
    
    para "this text is in normal styl" , emphasis:"italic"

    para "this text is in italic style" , font: "italic normal bold 16px/1.5 'Times New Roman', serif;"

    para "this text is in oblique style " , family: "'Pacifico', cursive;"

end
```
```
Shoes.app do

    para "This is Normal Variant" ,font_variant: "normal"


    para "This is Small Caps Variant " ,font_variant: "small-caps"

  end
```

### Image(if needed, helps for a faster review)

Screenshot 2024-01-30 at 7 26 17 PM

Screenshot 2024-01-30 at 7 27 17 PM

### Checklist

- [ ] Run tests locally

### CODE REVIEW

**Review by gintama91 — APPROVED** [review]

**Comment by noahgibbs** [comment]
Mostly this is really good. But it *does* seem to break the existing font functionality. Example:

```
Shoes.app do
  para "Text in Helvetica", font: "Helvetica", font_size: "20"

  para "And in Lucida", font: "Lucida", font_size: "20"

  para "From an example", :font => "Trebuchet 20px bold"
end
```

I think we're going to need some kind of parsing of the "font" property in Lacci for this.

**Comment by Nj221102** [comment]
this branch got a little messed up, I have solved the issue and will make a separate PR after closing this one,
sorry if it causes inconvenience  @noahgibbs

**Comment by noahgibbs** [comment]
All good, no trouble!

**Comment by Nj221102** [comment]
> All good, no trouble!

I have raised the new pull request #534  plz check it out.

**Pull request closed without merging**
