### PR TITLE
Initial 'build YARD on push' workflow

### PR DESCRIPTION
**Pull request by noahgibbs**
### Description

The intention is to start building docs, with YARD, on every code push. GH isn't running new actions on a draft PR, so I probably need to merge it to find out if it fully works :-(

### Checklist

- [ ] Run tests locally
- [ ] Run linter(check for linter errors)

### CODE REVIEW

**Comment by noahgibbs** [comment]
This doesn't seem to see the third workflow being added by this PR. That's understandable -- running untrusted workflows can be really bad. But it also makes this quite hard to debug properly :-)

**Comment by noahgibbs** [comment]
Okay, I'll mark this non-draft so it's possible to YOLO it.

**Review by Schwad — APPROVED** [review]
YOLOO

**Comment by Schwad** [comment]
I'm assuming you're happy to merge this? But I'll let you click it unless you wanted to still look at some things in ready-for-review mode

**Comment by noahgibbs** [comment]
Sounds good. Let's find out if it works!

**Comment by noahgibbs** [comment]
Nope. Okay, I'll work on the next form of this soon. In the mean time, I'll probably deactivate this so that it doesn't have a ton of failures for everybody :-(

**Pull request merged**
