### PR TITLE
Add support for para margin

### PR DESCRIPTION
**Pull request by zoomzam**
### Description

Add support for para margin

### Checklist

- [ ] Run tests locally

### CODE REVIEW

**Comment by noahgibbs** [comment]
I'm probably going to pull margin out of html_attributes, which doesn't really even work for what we're using it for, and put it in Drawable. We could pair on this if you'd like. But we don't really want to implement margin individually for each drawable, and it's actually supposed to work for basically all drawables.

**Comment by zoomzam** [comment]
okay, let's do it

**Comment by noahgibbs** [comment]
We'll probably want to wait until at least PR #473 is merged -- it touches some relevant stuff with initialize and styles. Once that's merged, I'm on UK time, but fairly free within that window. What time zone are you in?

**Comment by zoomzam** [comment]
GMT+5:30

**Comment by noahgibbs** [comment]
Okay. 473 is merged. I could be available tomorrow (Thurs) or Saturday if either of those works for you.

**Comment by zoomzam** [comment]
Saturday works!!

**Comment by noahgibbs** [comment]
Awesome. Let's plan on that. How does around 11am GMT work for you? So I assume that would be around 4:30pm in the afternoon.

**Comment by zoomzam** [comment]
sounds good

**Comment by noahgibbs** [comment]
Heya! It's around that time... Are you the same person as greenyblack in the Discord, or are you somebody else?

**Comment by noahgibbs** [comment]
I think we can close this now in favour of #489.

**Pull request closed without merging**
