### PR TITLE
list_box choose not working 

### PR DESCRIPTION
**Pull request by gintama91**
### Checklist

- [ ] Run tests locally

### CODE REVIEW

**Comment by gintama91** [comment]
list_box test didn't raised error as we check lb.text which basically is chosen

**Comment by gintama91** [comment]
wooh okay this is diff from what i normally expect it to do

code:
```
Shoes.app(width: 500, height: 450) do
  list_box height: "75",width:"150", items: ["dog", "cat", "bird"], choose: "orange"
  list_box :items => ["Jack", "Ace", "Joker"] , choose: "Ace"
end
```
output:
```
< div id = "2"
style = "display:flex;flex-direction:row;flex-wrap:wrap;align-content:flex-start;justify-content:flex-start;align-items:flex-start;width:100%" > < select id = "3"
onchange = "scarpeHandler('3-change', this.options[this.selectedIndex].value)"
style = "height:75;width:150" > < option value = "dog" > dog < /option><option value="cat">cat</option > < option value = "bird" > bird < /option></select > < select id = "4"
onchange = "scarpeHandler('4-change', this.options[this.selectedIndex].value)" > < option value = "Jack" > Jack < /option><option value="Ace" selected="true">Ace</option > < option value = "Joker" > Joker < /option></select > < div id = "root-fonts" > < /div><div id="root-alerts"> </div > < /div>

**Comment by gintama91** [comment]
lolol nvm🤣 damn i was passing orange in a listbox containing dog,cat,bird and wondering why cat is not rendering lol

**Comment by gintama91** [comment]
so i dont understand why this test_case is failing
```
x bundle exec ruby -Itest scarpe-components/test/calzini/test_calzini_misc.rb  
Started with run options --seed 9216

TestCalziniMiscDrawables
  test_list_box_simple                                            FAIL (0.00s)
        --- expected
        +++ actual
        @@ -1 +1 @@
        -"<select id=\"elt-1\" onchange=\"handle('change', this.options[this.selectedIndex].value)\" style=\"height:75;width:150\"><option value=\"dog\">dog</option><option value=\"cat\" selected=\"true\">cat</option><option value=\"bird\">bird</option></select>"
        +"<select id=\"elt-1\" onchange=\"handle('change', this.options[this.selectedIndex].value)\" style=\"height:75;width:150\"><option value=\"dog\">dog</option><option value=\"cat\">cat</option><option value=\"bird\">bird</option></select>"
        scarpe-components/test/calzini/test_calzini_misc.rb:76:in `test_list_box_simple'
     
  ```
  
  
  when i run same code and check for html it's showing cat has selected attribute...
  ```
  x ./exe/scarpe examples/list_box_choose.rb --dev
document.getElementById('wrapper-wvroot').innerHTML = `<div id="2" style="display:flex;flex-direction:row;flex-wrap:wrap;align-content:flex-start;justify-content:flex-start;align-items:flex-start;width:100%"><select id="3" onchange="scarpeHandler('3-change', this.options[this.selectedIndex].value)" style="height:75;width:150"><option value="dog">dog</option><option value="cat" selected="true">cat</option><option value="bird">bird</option></select><div id="root-fonts"></div><div id="root-alerts"> </div></div>`; true
```


code:
```
Shoes.app(width: 500, height: 450) do
  list_box height: "75",width:"150", :items=> ["dog", "cat", "bird"], choose: "cat"
end

```

@noahgibbs  any idea why actual output in test is not getting selected attribute for cat..?

**Comment by noahgibbs** [comment]
For the list_box_simple one, we changed the attr name to "chosen" instead of "choose", yeah? So the test is supplying the wrong property name in test_list_box_simple. Need to change "choose" to "chosen" in the test properties I think.

**Comment by gintama91** [comment]
This got bit messy and this is under `main` so making me hard for other pull requests. closing i will reopen or do this fix in some other pr.

**Pull request closed without merging**
