### PR TITLE
More timeout options for sspec tests

### PR DESCRIPTION
**Pull request by noahgibbs**
### Description

Our pre-Shoes-Spec test infrastructure had a bunch of timeout and failure options. Turns out I need some of those for testing display properties, too. So I'm adding them for Shoes-Spec.

### Checklist

- [X] Run tests locally

### CODE REVIEW

**Comment by noahgibbs** [comment]
Hm. This is succeeding in its tests, but it's not doing quite the right thing. I'll fix it before I merge.

**Comment by noahgibbs** [comment]
Huh. Calling exit(-1) in a Fiber seems to not be actually exiting the process. Either that or I'm not understanding what's happening somehow.

**Comment by noahgibbs** [comment]
In a tiny test program, exit called from a Fiber works fine. Maybe it's some kind of Webview thing?

**Comment by noahgibbs** [comment]
Okay. Worked around this for the cases I care about. Still a large improvement on *not* having this.

**Comment by noahgibbs** [comment]
May just merge this. Updating to main in any case.

**Review by Schwad — APPROVED** [review]

**Pull request merged**
